---
name: infrastructure-flow
on:
  workflow_call:
    inputs:
      bucket_name:
        description: "Name of the S3 bucket"
        required: true
        type: string
      tfvar_file_path:
        description: "Path to the tfvar file"
        required: true
        type: string
      approvers:
        description: "List of approvers"
        required: true
        type: string
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
jobs:
  infrastructure-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout oc-terraform-module-eks-setup
        uses: actions/checkout@v4
        with:
          repository: orbitcluster/oc-terraform-module-eks-setup
          path: oc-terraform-module-eks-setup
          ref: dk/changestrategy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: ./oc-terraform-module-eks-setup/.github/actions/terraform-setup

      - name: eks_infra
        uses: ./oc-terraform-module-eks-setup/.github/actions/terraform-plan-apply
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./oc-terraform-module-eks-setup/eks_infra
          approvers: ${{ inputs.approvers }}
          component: eks_infra
          cluster_name: ${{ inputs.cluster_name }}

      # - name: eks_essential_addons
      #   uses: ./oc-terraform-module-eks-setup/.github/actions/terraform
      #   with:
      #     bucket_name: ${{ inputs.bucket_name }}
      #     tfvar_file_path: ${{ inputs.tfvar_file_path }}
      #     directory: ./oc-terraform-module-eks-setup/eks-essential-addons
      #     approvers: ${{ inputs.approvers }}
